### ISSUE TITLE
EADDRINUSE port conflicts in headless Cypress runs with cypress-ntlm-auth 4.x (works fine headed)

### ISSUE THREAD

**Issue by DanieTheTester** [bjowes/cypress-ntlm-auth#264]
Hi Björn,

I’ve been using cypress-ntlm-auth successfully for some time with Cypress. Recently, I started experiencing consistent issues only during headless runs and pipelines.

Issue History:

Phase 1 :  NO_PROXY "<-loopback>" error

At first, I encountered this error:      Invalid NO_PROXY argument part '<-loopback>'
I resolved this by sanitizing the NO_PROXY value in my `.env` and adding runtime sanitization in my `cypress.config.js`.  
This fixed the NO_PROXY error.

Phase 2: EADDRINUSE port conflicts
After fixing NO_PROXY, new errors appeared: Error: listen EADDRINUSE: Address already in use 127.0.0.1:XXXXX

In headed runs (Cypress open / interactive browser), everything works fine.

In headless runs (npx cypress run, or CI/CD pipelines), I get random port conflicts: Error: listen EADDRINUSE: address already in use 127.0.0.1:xxxxx

This happens at different port numbers every time (ephemeral ports).

What I’ve tried:

- Locked NTLM proxy port using `NTLM_PROXY_PORT`.
- Patched NTLM proxy to always bind to the specified port (see attached patch).
- Cleaned invalid NO_PROXY values at runtime.
- Forced Chrome remote-debugging-port to 9222.
- Killed all lingering Node.js processes between runs.
- Added port availability checks before each test run.
- Downgraded from Node 20 to Node 18.

The NTLM proxy binds correctly.  
EADDRINUSE errors persist ; but only on random high ports not under my control.

Key findings:

-Headless runs repeatedly cause dynamic port collisions, even when the NTLM proxy itself binds to a fixed port.
-The problem seems related to Cypress internal web server or dynamic ephemeral port reuse when Cypress runs headless (perhaps due to fast parallel tests or rapid retries) perhaps?

Even though my NTLM proxy binds to a fixed port, random collisions still occur at runtime.

Attachments:
- Patch: `cypress-ntlm-auth+4.1.7.patch`
- `cypress.config.js`
- sanitize-env.js
- run-test.sh

[Cypress_NTLM_Issue_Files.pdf](https://github.com/user-attachments/files/20033695/Cypress_NTLM_Issue_Files.pdf)

(All sensitive details have been removed. Hostnames changed to `example-internal-app.test`.)

Help requested:
-Is there a recommended way to prevent Cypress and cypress-ntlm-auth from conflicting on ephemeral ports in headless runs?
-Is there a plan to support more stable NTLM proxy port reuse in 4.x?
-Any workarounds you would recommend, please?

Thank you very much for your support and this essential plugin!

Kind regards
Daniella

**Comment by bjowes** [comment]
Hi,

Thanks for the detailed issue report, it really helps!

Preliminary answers:

1) Which component is throwing the NO_PROXY error? The rather odd format
'<-loopback>' has been the standard way for Cypress to ensure traffic to
localhost is sent through the proxy, which is needed when the target of the
cypress tests is also running on localhost. My first guess is that the
error comes from an updated component (could be NodeJS, Cypress, the
browser, other plugins or some library).

2) Fixating the ports only fixates two ports - one for the NTLM proxy
endpoint and one for the NTLM proxy configuration API endpoint. In
addition, other ports will be allocated dynamically as required by incoming
requests. This allocation should respect ports that are already in use, so
unless the ports are exhausted I don't see where the error is coming from.
There is already built-in support for setting specific ports by
using CYPRESS_NTLM_AUTH_API and CYPRESS_NTLM_AUTH_PROXY environment
variables, see the Readme. But as stated, this only affects two ports
allocated during startup, I don't think these are your issue. My
preliminary guess is that incorrect NO_PROXY config is causing the issue,
and given that you only see it in headless mode it could be related to the
browser version.

/Björn

**Comment by DanieTheTester** [comment]
Hi Björn,

Thank you for your response. Following up on your question about which component is throwing the NO_PROXY error:

During the Phase 1 issue (before applying any sanitization), the NO_PROXY error was being thrown by cypress-ntlm-auth itself, specifically in: UpstreamProxyManager.validateNoProxyPart 
(line 82 in upstream.proxy.manager.js)

The error occurs when the startNtlmProxy() function runs inside the Cypress before:run hook. It appears the plugin is attempting to validate the NO_PROXY environment variable at that point and throws the error if it contains the <-loopback> entry.

Here’s the full stack trace:
An error was thrown in your plugins file while executing the handler for the before:run event.

The error we received was:

Error: Invalid NO_PROXY argument part '<-loopback>'. It must be a comma separated list of: valid IP, hostname[:port] or a wildcard prefixed hostname. Protocol shall not be included. IPv6 addresses must be quoted in []. Examples: localhost,127.0.0.1,[::1],noproxy.acme.com:8080,*.noproxy.com
    at UpstreamProxyManager.validateNoProxyPart (cypress-ntlm-auth/dist/proxy/upstream.proxy.manager.js:82:15)
    at cypress-ntlm-auth/dist/proxy/upstream.proxy.manager.js:51:54
    at Array.map (<anonymous>)
    at UpstreamProxyManager.init (cypress-ntlm-auth/dist/proxy/upstream.proxy.manager.js:47:52)
    at CoreServer.<anonymous> (cypress-ntlm-auth/dist/proxy/core.server.js:61:40)
    at Generator.next (<anonymous>)
    at cypress-ntlm-auth/dist/proxy/core.server.js:20:71
    at new Promise (<anonymous>)
    at _ _awaiter (cypress-ntlm-auth/dist/proxy/core.server.js:16:12)
    at CoreServer.start (cypress-ntlm-auth/dist/proxy/core.server.js:60:16)
    at Main.<anonymous> (cypress-ntlm-auth/dist/proxy/main.js:52:54)
    at Generator.next (<anonymous>)
    at cypress-ntlm-auth/dist/proxy/main.js:20:71
    at new Promise (<anonymous>)
    at _ _awaiter (cypress-ntlm-auth/dist/proxy/main.js:16:12)
    at Main.run (cypress-ntlm-auth/dist/proxy/main.js:50:16)
    at Startup.<anonymous> (cypress-ntlm-auth/dist/startup/startup.js:125:42)
    at Generator.next (<anonymous>)
    at cypress-ntlm-auth/dist/startup/startup.js:20:71
    at new Promise (<anonymous>)
    at _ _awaiter (cypress-ntlm-auth/dist/startup/startup.js:16:12)
    at Startup.startNtlmProxy (cypress-ntlm-auth/dist/startup/startup.js:121:16)
    at cypress-ntlm-auth/dist/index.js:71:37
    at Generator.next (<anonymous>)
    at cypress-ntlm-auth/dist/index.js:8:71
    at new Promise (<anonymous>)
    at _ _awaiter (cypress-ntlm-auth/dist/index.js:4:12)
    at startNtlmProxy (cypress-ntlm-auth/dist/index.js:68:12)

If there are any diagnostic steps you recommend to trace how NO_PROXY or ports are modified during headless runs, I would be happy to try them. Also, if there are flags to prevent headless Chrome or Cypress from injecting NO_PROXY values like '<-loopback>', I’d like to apply those too. Thank you.

Daniella

**Comment by bjowes** [comment]
It could be that '<-loopback>' is not properly handled by the plugin, I
will investigate later.
Could you try changing the NO_PROXY env variable and remove the <-loopback>
part? Then run the plugin without your customizations that tries to
sanitize the NO_PROXY string.
By the way, do you know why your NO_PROXY string includes this? It should
generally not be needed.

**Comment by bjowes** [comment]
The bug of incorrect handling och '<-loopback>' has been fixed in version 4.2.2 which was just released.

**Comment by DanieTheTester** [comment]
I upgraded to cypress-ntlm-auth 4.2.2 and removed all customizations (no NO_PROXY override, no NTLM proxy port patching, and no sanitize-env.js).

The '<-loopback>' NO_PROXY issue is now fully resolved. Thank you very much.

However, the dynamic port conflict (EADDRINUSE) issue still occurs.

Here's the error from the clean run:

before:run → Starting NTLM proxy...
Error: listen EADDRINUSE: address already in use 127.0.0.1:50606

This confirms that even without any overrides, dynamic ports used by the proxy (or Cypress internals) are still colliding in headless mode.

Thank you again for the Phase 1 fix.

**Comment by bjowes** [comment]
Great!

From the stacktrace of the EADDRINUSE error, it seems that Cypress fails to allocate the port (not the plugin). Is it possible to run the test (or a similar one) without the plugin and see if the same issue occurs?

Using the plugin will require use of more ports, since the ntlm-proxy creates virtual HTTP servers to be able to handle the NTLM authentication. But this should not be a large number of ports, unless for some reason the browser is immediately closing its connections, forcing use of new ports on each request. You should be able to follow this in the debug log of the plugin, where all ports are logged. Try to see if a huge number of ports are getting allocated.

**Comment by DanieTheTester** [comment]
As requested, I temporarily removed all NTLM plugin code from both cypress.config.js and e2e.js. All NTLM proxy logic and commands were fully disabled. I then ran the same test in headless mode.

Result:

Cypress launched successfully.
No EADDRINUSE (port binding) errors occurred.
The only failure was an expected 401 Unauthorized error from the test app, since NTLM credentials were not provided.

It seems like Cypress alone does not hit EADDRINUSE  errors

Here's the relevant error from cypress:

CypressError: cy.visit() failed trying to load:
https://example.com/
The response we received from your web server was:
  > 401: Unauthorized
This was considered a failure because the status code was not 2xx.
Because this error occurred during a before each hook we are skipping all of the remaining tests.

**Comment by DanieTheTester** [comment]
My test framework relies 100% on the NTLM plugin, running 14 spec files.

Average duration: ~11 minutes total.
Nature of tests: UI/end-to-end tests involving page loads, form interactions, and API calls.
Average per spec: ~40–60 seconds each, multiple network requests per test.

As a control, I created a non-NTLM test suite using example.io, it completed fully without any EADDRINUSE errors.

Here’s the result:
Running:  basic-non-ntlm.cy.js  (1 of 1)
  Non-NTLM basic test
   should visit a public site and perform simple actions (1157ms)
  1 passing (3s)

 Next, I'll now rebuild my NTLM Tests config.js and e2e.js files to fully align with NTLM plugin version 4.2.2. I’ll report back once I’ve tested the updated configuration.

Thanks again for your help.

**Comment by bjowes** [comment]
Please note that 4.2.3 was released recently when fixing another issue. So please use that one for further tests. It does not require any configuration changes in your test setup.

**Comment by bjowes** [comment]
Also, since you started seeing these issues recently, please try to find a working version (go back to an earlier version of your repo) and check what has changed. Updates to cypress or other libraries, changes in test procedures?

In the test suite of cypress-ntlm-auth there is a step that runs hundreds of requests through the proxy, and this still works fine.

**Comment by DanieTheTester** [comment]
Hi Björn,

Just wanted to update you that the issue has now been successfully resolved. I have stabilized the setup and removed all manual startNtlmProxy and stopNtlmProxy logic from cypress.config.  Also updated to 4.2.3. With these in place, the test suite now runs cleanly both in headless and headed modes without encountering EADDRINUSE error. Thank you so much for your help and responsiveness; and for the latest improvements to the plugins.

Appreciate your help in getting back on track. Really great support!
